/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssessmentRouteImport } from './routes/_authenticated/assessment'
import { Route as AuthenticatedAssessmentResultsRouteImport } from './routes/_authenticated/assessment-results'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedCareersRouteImport } from './routes/_authenticated/careers'
import { Route as AuthenticatedCollegesRouteImport } from './routes/_authenticated/colleges'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedResourcesRouteImport } from './routes/_authenticated/resources'
import { Route as AuthenticatedResumeRouteImport } from './routes/_authenticated/resume'
import { Route as AuthenticatedScholarshipsRouteImport } from './routes/_authenticated/scholarships'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSkillGapRouteImport } from './routes/_authenticated/skill-gap'
import { Route as AuthenticatedStudyPlannerRouteImport } from './routes/_authenticated/study-planner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentRoute = AuthenticatedAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentResultsRoute =
  AuthenticatedAssessmentResultsRouteImport.update({
    id: '/assessment-results',
    path: '/assessment-results',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareersRoute = AuthenticatedCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollegesRoute = AuthenticatedCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourcesRoute = AuthenticatedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumeRoute = AuthenticatedResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScholarshipsRoute =
  AuthenticatedScholarshipsRouteImport.update({
    id: '/scholarships',
    path: '/scholarships',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSkillGapRoute = AuthenticatedSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudyPlannerRoute =
  AuthenticatedStudyPlannerRouteImport.update({
    id: '/study-planner',
    path: '/study-planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/assessment-results': typeof AuthenticatedAssessmentResultsRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/careers': typeof AuthenticatedCareersRoute
  '/colleges': typeof AuthenticatedCollegesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/scholarships': typeof AuthenticatedScholarshipsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
  '/study-planner': typeof AuthenticatedStudyPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assessment': typeof AuthenticatedAssessmentRoute
  '/assessment-results': typeof AuthenticatedAssessmentResultsRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/careers': typeof AuthenticatedCareersRoute
  '/colleges': typeof AuthenticatedCollegesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exams': typeof AuthenticatedExamsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/resources': typeof AuthenticatedResourcesRoute
  '/resume': typeof AuthenticatedResumeRoute
  '/scholarships': typeof AuthenticatedScholarshipsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/skill-gap': typeof AuthenticatedSkillGapRoute
  '/study-planner': typeof AuthenticatedStudyPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assessment': typeof AuthenticatedAssessmentRoute
  '/_authenticated/assessment-results': typeof AuthenticatedAssessmentResultsRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/careers': typeof AuthenticatedCareersRoute
  '/_authenticated/colleges': typeof AuthenticatedCollegesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/_authenticated/resources': typeof AuthenticatedResourcesRoute
  '/_authenticated/resume': typeof AuthenticatedResumeRoute
  '/_authenticated/scholarships': typeof AuthenticatedScholarshipsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/skill-gap': typeof AuthenticatedSkillGapRoute
  '/_authenticated/study-planner': typeof AuthenticatedStudyPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/assessment'
    | '/assessment-results'
    | '/bookmarks'
    | '/careers'
    | '/colleges'
    | '/dashboard'
    | '/exams'
    | '/profile'
    | '/progress'
    | '/resources'
    | '/resume'
    | '/scholarships'
    | '/settings'
    | '/skill-gap'
    | '/study-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/assessment'
    | '/assessment-results'
    | '/bookmarks'
    | '/careers'
    | '/colleges'
    | '/dashboard'
    | '/exams'
    | '/profile'
    | '/progress'
    | '/resources'
    | '/resume'
    | '/scholarships'
    | '/settings'
    | '/skill-gap'
    | '/study-planner'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/assessment'
    | '/_authenticated/assessment-results'
    | '/_authenticated/bookmarks'
    | '/_authenticated/careers'
    | '/_authenticated/colleges'
    | '/_authenticated/dashboard'
    | '/_authenticated/exams'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/_authenticated/resources'
    | '/_authenticated/resume'
    | '/_authenticated/scholarships'
    | '/_authenticated/settings'
    | '/_authenticated/skill-gap'
    | '/_authenticated/study-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment': {
      id: '/_authenticated/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AuthenticatedAssessmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessment-results': {
      id: '/_authenticated/assessment-results'
      path: '/assessment-results'
      fullPath: '/assessment-results'
      preLoaderRoute: typeof AuthenticatedAssessmentResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/careers': {
      id: '/_authenticated/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof AuthenticatedCareersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colleges': {
      id: '/_authenticated/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof AuthenticatedCollegesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resources': {
      id: '/_authenticated/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthenticatedResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume': {
      id: '/_authenticated/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof AuthenticatedResumeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scholarships': {
      id: '/_authenticated/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof AuthenticatedScholarshipsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skill-gap': {
      id: '/_authenticated/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof AuthenticatedSkillGapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/study-planner': {
      id: '/_authenticated/study-planner'
      path: '/study-planner'
      fullPath: '/study-planner'
      preLoaderRoute: typeof AuthenticatedStudyPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssessmentRoute: typeof AuthenticatedAssessmentRoute
  AuthenticatedAssessmentResultsRoute: typeof AuthenticatedAssessmentResultsRoute
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedCareersRoute: typeof AuthenticatedCareersRoute
  AuthenticatedCollegesRoute: typeof AuthenticatedCollegesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedResourcesRoute: typeof AuthenticatedResourcesRoute
  AuthenticatedResumeRoute: typeof AuthenticatedResumeRoute
  AuthenticatedScholarshipsRoute: typeof AuthenticatedScholarshipsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSkillGapRoute: typeof AuthenticatedSkillGapRoute
  AuthenticatedStudyPlannerRoute: typeof AuthenticatedStudyPlannerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssessmentRoute: AuthenticatedAssessmentRoute,
  AuthenticatedAssessmentResultsRoute: AuthenticatedAssessmentResultsRoute,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedCareersRoute: AuthenticatedCareersRoute,
  AuthenticatedCollegesRoute: AuthenticatedCollegesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedResourcesRoute: AuthenticatedResourcesRoute,
  AuthenticatedResumeRoute: AuthenticatedResumeRoute,
  AuthenticatedScholarshipsRoute: AuthenticatedScholarshipsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSkillGapRoute: AuthenticatedSkillGapRoute,
  AuthenticatedStudyPlannerRoute: AuthenticatedStudyPlannerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
